# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Xueying's some goods for X-ray universe
email: xyzheng@nao.cas.cn
description: All the models are wrong, but some are good.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://astroxyzheng.github.io" # the base hostname & protocol for your site
twitter_username: XueyingChar
github_username:  astroxyzheng
paginate: 5
theme-dark: true #Set to true to change to dark website theme
tagline: "This is a custom tagline content which overrides the default page excerpt."
header:
  overlay_image: /m31xray.png
  caption: "Photo credit: [**Unsplash**](https://unsplash.com)"
  
plugins: [jekyll-paginate, kramdown]
# Build settings
markdown: kramdown
